# Generated by Django 4.1.3 on 2022-11-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('UNPUB', 'Unpublished'), ('DR', 'Draft'), ('ARC', 'Archived')], default='PUB', max_length=6)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'db_category',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='db_category_name_82a438_idx'),
        ),
    ]
