# Generated by Django 4.1.3 on 2022-12-02 17:26

import apps.about.utils
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.about.utils.about_image_directory_path)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'db_about',
            },
        ),
        migrations.AddIndex(
            model_name='about',
            index=models.Index(fields=['title'], name='db_about_title_5dcc35_idx'),
        ),
    ]
