# Generated by Django 4.1.3 on 2022-12-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'db_table': 'db_contact_info',
            },
        ),
        migrations.AddIndex(
            model_name='contactinfo',
            index=models.Index(fields=['title'], name='db_contact__title_cef464_idx'),
        ),
    ]
