# Generated by Django 4.1.3 on 2022-11-29 18:46

import apps.feature.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=apps.feature.utils.extend_image_directory_path)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('UNPUB', 'Unpublished'), ('DR', 'Draft'), ('ARC', 'Archived')], default='PUB', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Extend Blog',
                'verbose_name_plural': 'Extend Blog',
                'db_table': 'db_extend_blog',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter', models.URLField(blank=True, max_length=300, null=True)),
                ('instagram', models.URLField(blank=True, max_length=300, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=300, null=True)),
                ('pintest', models.URLField(blank=True, max_length=300, null=True)),
                ('youtube', models.URLField(blank=True, max_length=300, null=True)),
                ('stack_overflow', models.URLField(blank=True, max_length=300, null=True)),
                ('dev_to', models.URLField(blank=True, max_length=300, null=True)),
                ('figma', models.URLField(blank=True, max_length=300, null=True)),
                ('medium', models.URLField(blank=True, max_length=300, null=True)),
                ('github', models.URLField(blank=True, max_length=300, null=True)),
                ('gitlab', models.URLField(blank=True, max_length=300, null=True)),
                ('bitbucket', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'db_table': 'db_social_media',
            },
        ),
    ]
