# Generated by Django 4.1.3 on 2022-11-13 20:09

import apps.blog.utils
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.blog.utils.post_image_directory_path)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_feature', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=500)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('UNPUB', 'Unpublished'), ('DR', 'Draft'), ('ARC', 'Archived')], default='PUB', max_length=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='post_create', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'db_blog',
                'ordering': ('-published',),
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published'], name='db_blog_publish_9646b4_idx'),
        ),
    ]
